# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\render_code\checkMayaFile\projectList.ui',
# licensing of 'D:\render_code\checkMayaFile\projectList.ui' applies.
#
# Created: Fri Jul 12 16:25:30 2019
#      by: pyside2-uic  running on PySide2 5.11.4a1.dev1546291887
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_projectListDialog(object):
    def setupUi(self, projectListDialog):
        projectListDialog.setObjectName("projectListDialog")
        projectListDialog.resize(1082, 738)
        self.gridLayout = QtWidgets.QGridLayout(projectListDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(projectListDialog)
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.mayaVersionComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.mayaVersionComboBox.setObjectName("mayaVersionComboBox")
        self.horizontalLayout_2.addWidget(self.mayaVersionComboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.renderComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.renderComboBox.setObjectName("renderComboBox")
        self.horizontalLayout_2.addWidget(self.renderComboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.projectListWidget = QtWidgets.QTableWidget(self.groupBox_3)
        self.projectListWidget.setObjectName("projectListWidget")
        self.projectListWidget.setColumnCount(1)
        self.projectListWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.projectListWidget.setHorizontalHeaderItem(0, item)
        self.gridLayout_3.addWidget(self.projectListWidget, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.resourcePathEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.resourcePathEdit.setObjectName("resourcePathEdit")
        self.horizontalLayout.addWidget(self.resourcePathEdit)
        self.pathBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.pathBtn.setObjectName("pathBtn")
        self.horizontalLayout.addWidget(self.pathBtn)
        self.refreshBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.refreshBtn.setObjectName("refreshBtn")
        self.horizontalLayout.addWidget(self.refreshBtn)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_3, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(projectListDialog)
        QtCore.QMetaObject.connectSlotsByName(projectListDialog)

    def retranslateUi(self, projectListDialog):
        projectListDialog.setWindowTitle(QtWidgets.QApplication.translate("projectListDialog", "Dialog", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("projectListDialog", "Render setting", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("projectListDialog", "Maya version", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("projectListDialog", "Render Information", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("projectListDialog", "Project info", None, -1))
        self.projectListWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("projectListDialog", "Projectpath", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("projectListDialog", "Resource path :", None, -1))
        self.pathBtn.setText(QtWidgets.QApplication.translate("projectListDialog", "path", None, -1))
        self.refreshBtn.setText(QtWidgets.QApplication.translate("projectListDialog", "refresh", None, -1))

